//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.BLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRange
    {
        public int SalaryRange_ID { get; set; }
        public string Salary_Com_Key { get; set; }
        public string Applicable_Grid { get; set; }
        public string Org_1 { get; set; }
        public string Org_2 { get; set; }
        public string Org_3 { get; set; }
        public string Job_Family { get; set; }
        public string Job_SubFamily { get; set; }
        public string Grade { get; set; }
        public string Title { get; set; }
        public string PeopleSoft_Location { get; set; }
        public string Location { get; set; }
        public string Salary_Range_Minimum { get; set; }
        public string Salary_Range_Midpoint { get; set; }
        public string Salary_Range_Maximum { get; set; }
        public string TC_Range_Minimum { get; set; }
        public string TC_Range_Midpoint { get; set; }
        public string TC_Range_Maximum { get; set; }
        public string TC_Min_Tier { get; set; }
        public string TC_Midpoint_Tier { get; set; }
        public string TC_Max_Tier { get; set; }
        public System.DateTime Updated_Date { get; set; }
    }
}
